version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: order-postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: order-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - order-network

  order-api:
    build: .
    container_name: order-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orders
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_pass
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - order-network

volumes:
  postgres_data:

networks:
  order-network:
    driver: bridge
